# Generated by Django 5.0.6 on 2026-06-05 05:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_add_google_fields'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alertestock',
            options={'verbose_name': 'Alerte stock', 'verbose_name_plural': 'Alertes stock'},
        ),
        migrations.AlterModelOptions(
            name='articleblog',
            options={'ordering': ['-date_publication'], 'verbose_name': 'Article de blog', 'verbose_name_plural': 'Articles de blog'},
        ),
        migrations.AlterModelOptions(
            name='bienfait',
            options={'ordering': ['ordre'], 'verbose_name': 'Bienfait', 'verbose_name_plural': 'Bienfaits'},
        ),
        migrations.AlterModelOptions(
            name='blacklist',
            options={'ordering': ['-date_ajout'], 'verbose_name': 'Blacklist', 'verbose_name_plural': 'Blacklist'},
        ),
        migrations.AlterModelOptions(
            name='codepromo',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Code Promo', 'verbose_name_plural': 'Codes Promo'},
        ),
        migrations.AlterModelOptions(
            name='commande',
            options={'ordering': ['-date_commande'], 'verbose_name': 'Commande'},
        ),
        migrations.AlterModelOptions(
            name='configaccueil',
            options={'verbose_name': "Configuration Page d'accueil", 'verbose_name_plural': "Configuration Page d'accueil"},
        ),
        migrations.AlterModelOptions(
            name='configsite',
            options={'verbose_name': 'Configuration Globale du Site', 'verbose_name_plural': 'Configuration Globale du Site'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['ordre'], 'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQ'},
        ),
        migrations.AlterModelOptions(
            name='fondateurconfig',
            options={'verbose_name': 'Configuration Fondateur', 'verbose_name_plural': 'Configuration Fondateur'},
        ),
        migrations.AlterModelOptions(
            name='histoirechapitre',
            options={'ordering': ['ordre'], 'verbose_name': "Chapitre de l'histoire", 'verbose_name_plural': "Chapitres de l'histoire"},
        ),
        migrations.AlterModelOptions(
            name='historiquecommande',
            options={'ordering': ['-date'], 'verbose_name': 'Historique commande', 'verbose_name_plural': 'Historiques commandes'},
        ),
        migrations.AlterModelOptions(
            name='lignecommande',
            options={'verbose_name': 'Ligne de commande'},
        ),
        migrations.AlterModelOptions(
            name='logconnexion',
            options={'ordering': ['-date'], 'verbose_name': 'Log connexion', 'verbose_name_plural': 'Logs connexions'},
        ),
        migrations.AlterModelOptions(
            name='messagecontact',
            options={'ordering': ['-date_envoi'], 'verbose_name': 'Message de contact'},
        ),
        migrations.AlterModelOptions(
            name='mission',
            options={'ordering': ['ordre'], 'verbose_name': 'Mission', 'verbose_name_plural': 'Missions'},
        ),
        migrations.AlterModelOptions(
            name='newsletterabonne',
            options={'ordering': ['-date_inscription'], 'verbose_name': 'Abonne Newsletter', 'verbose_name_plural': 'Abonnes Newsletter'},
        ),
        migrations.AlterModelOptions(
            name='paniersauvegarde',
            options={'verbose_name': 'Panier sauvegardé'},
        ),
        migrations.AlterModelOptions(
            name='partenaire',
            options={'ordering': ['ordre'], 'verbose_name': 'Partenaire', 'verbose_name_plural': 'Partenaires'},
        ),
        migrations.AlterModelOptions(
            name='produit',
            options={'verbose_name': 'Produit'},
        ),
        migrations.AlterModelOptions(
            name='reponseavis',
            options={'verbose_name': 'Réponse avis', 'verbose_name_plural': 'Réponses avis'},
        ),
        migrations.AlterModelOptions(
            name='resetpasswordtoken',
            options={'ordering': ['-cree_le'], 'verbose_name': 'Token réinitialisation mot de passe'},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'ordering': ['ordre'], 'verbose_name': 'Slider / Banniere', 'verbose_name_plural': 'Sliders / Bannieres'},
        ),
        migrations.AlterModelOptions(
            name='temoignage',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Temoignage'},
        ),
        migrations.AlterModelOptions(
            name='utilisateur',
            options={'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Utilisateurs'},
        ),
        migrations.AlterModelOptions(
            name='zonelivraison',
            options={'ordering': ['ordre', 'ville'], 'verbose_name': 'Zone de livraison', 'verbose_name_plural': 'Zones de livraison'},
        ),
        migrations.RenameField(
            model_name='partenaire',
            old_name='site',
            new_name='lien',
        ),
        migrations.RemoveField(
            model_name='articleblog',
            name='auteur',
        ),
        migrations.RemoveField(
            model_name='configaccueil',
            name='hero_bouton',
        ),
        migrations.RemoveField(
            model_name='configaccueil',
            name='hero_image',
        ),
        migrations.RemoveField(
            model_name='configaccueil',
            name='hero_sous_titre',
        ),
        migrations.RemoveField(
            model_name='configaccueil',
            name='hero_titre',
        ),
        migrations.RemoveField(
            model_name='configaccueil',
            name='section_bienfaits_titre',
        ),
        migrations.RemoveField(
            model_name='configaccueil',
            name='section_produits_titre',
        ),
        migrations.RemoveField(
            model_name='configaccueil',
            name='section_temoignages_titre',
        ),
        migrations.RemoveField(
            model_name='configsite',
            name='couleur_primaire',
        ),
        migrations.RemoveField(
            model_name='configsite',
            name='couleur_secondaire',
        ),
        migrations.RemoveField(
            model_name='configsite',
            name='email_contact',
        ),
        migrations.RemoveField(
            model_name='configsite',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='configsite',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='configsite',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='configsite',
            name='nom_site',
        ),
        migrations.RemoveField(
            model_name='configsite',
            name='slogan',
        ),
        migrations.RemoveField(
            model_name='configsite',
            name='whatsapp',
        ),
        migrations.RemoveField(
            model_name='fondateurconfig',
            name='biographie',
        ),
        migrations.RemoveField(
            model_name='fondateurconfig',
            name='titre',
        ),
        migrations.RemoveField(
            model_name='histoirechapitre',
            name='contenu',
        ),
        migrations.RemoveField(
            model_name='messagecontact',
            name='sujet',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='description',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='titre',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='ordre',
        ),
        migrations.RemoveField(
            model_name='resetpasswordtoken',
            name='expire_a',
        ),
        migrations.RemoveField(
            model_name='temoignage',
            name='commentaire',
        ),
        migrations.RemoveField(
            model_name='temoignage',
            name='email',
        ),
        migrations.RemoveField(
            model_name='temoignage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='temoignage',
            name='video_url',
        ),
        migrations.AddField(
            model_name='articleblog',
            name='categorie',
            field=models.CharField(blank=True, default='Sante naturelle', max_length=100),
        ),
        migrations.AddField(
            model_name='articleblog',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articleblog',
            name='date_modif',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='articleblog',
            name='temps_lecture',
            field=models.CharField(default='3 min', max_length=20),
        ),
        migrations.AddField(
            model_name='commande',
            name='date_mise_a_jour',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='configaccueil',
            name='cta_bouton',
            field=models.CharField(default='Commander dès 2 500 FCFA', max_length=100),
        ),
        migrations.AddField(
            model_name='configaccueil',
            name='cta_label',
            field=models.CharField(default='Prêt à prendre soin de vous ?', max_length=200),
        ),
        migrations.AddField(
            model_name='configaccueil',
            name='cta_lien',
            field=models.CharField(default='/boutique', max_length=200),
        ),
        migrations.AddField(
            model_name='configaccueil',
            name='cta_texte',
            field=models.TextField(default="Commandez votre Thé Pio Pio dès aujourd'hui."),
        ),
        migrations.AddField(
            model_name='configaccueil',
            name='tasse_bouton',
            field=models.CharField(default='Commander maintenant', max_length=100),
        ),
        migrations.AddField(
            model_name='configaccueil',
            name='tasse_citation',
            field=models.TextField(default="Redécouvrez le plaisir d'un moment de calme"),
        ),
        migrations.AddField(
            model_name='configaccueil',
            name='tasse_image',
            field=models.ImageField(blank=True, help_text='Image de fond de la section tasse. Taille recommandée : 1920x600px.', null=True, upload_to='accueil/'),
        ),
        migrations.AddField(
            model_name='configaccueil',
            name='tasse_label',
            field=models.CharField(default='Un moment rien que pour vous', max_length=200),
        ),
        migrations.AddField(
            model_name='configaccueil',
            name='tasse_lien',
            field=models.CharField(default='/boutique', max_length=200),
        ),
        migrations.AddField(
            model_name='configsite',
            name='argument1_icone',
            field=models.CharField(default='🌱', max_length=10),
        ),
        migrations.AddField(
            model_name='configsite',
            name='argument1_sous',
            field=models.CharField(default='Sans engrais ni herbicides', max_length=200),
        ),
        migrations.AddField(
            model_name='configsite',
            name='argument1_titre',
            field=models.CharField(default='100 % Bio', max_length=100),
        ),
        migrations.AddField(
            model_name='configsite',
            name='argument2_icone',
            field=models.CharField(default='🔬', max_length=10),
        ),
        migrations.AddField(
            model_name='configsite',
            name='argument2_sous',
            field=models.CharField(default='Formulé par un vétérinaire', max_length=200),
        ),
        migrations.AddField(
            model_name='configsite',
            name='argument2_titre',
            field=models.CharField(default='Fondé sur la science', max_length=100),
        ),
        migrations.AddField(
            model_name='configsite',
            name='argument3_icone',
            field=models.CharField(default='👨\u200d👩\u200d👧', max_length=10),
        ),
        migrations.AddField(
            model_name='configsite',
            name='argument3_sous',
            field=models.CharField(default='Recommandé dès 2 ans', max_length=200),
        ),
        migrations.AddField(
            model_name='configsite',
            name='argument3_titre',
            field=models.CharField(default='Toute la famille', max_length=100),
        ),
        migrations.AddField(
            model_name='configsite',
            name='argument4_icone',
            field=models.CharField(default='🇧🇯', max_length=10),
        ),
        migrations.AddField(
            model_name='configsite',
            name='argument4_sous',
            field=models.CharField(default='Livraison nationale', max_length=200),
        ),
        migrations.AddField(
            model_name='configsite',
            name='argument4_titre',
            field=models.CharField(default='Made in Bénin', max_length=100),
        ),
        migrations.AddField(
            model_name='configsite',
            name='description_footer',
            field=models.TextField(default='Thé 100% naturel à base de verveine blanche citronnée. Cultivé et produit à Porto-Novo, Bénin.', help_text='Texte sous le logo dans le footer.'),
        ),
        migrations.AddField(
            model_name='configsite',
            name='email',
            field=models.EmailField(default='tropicanapiopio@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='configsite',
            name='facebook_url',
            field=models.URLField(blank=True, default='https://facebook.com/profile.php?id=61569744814995'),
        ),
        migrations.AddField(
            model_name='configsite',
            name='paiements',
            field=models.CharField(default='MTN Money,Moov Money,Wave,Orange', help_text='Modes de paiement séparés par des virgules. Ex: MTN Money,Moov Money,Wave', max_length=500),
        ),
        migrations.AddField(
            model_name='configsite',
            name='prix_affiche',
            field=models.CharField(default='dès 2 500 FCFA', help_text='Prix affiché sur les boutons CTA. Ex: dès 2 500 FCFA', max_length=100),
        ),
        migrations.AddField(
            model_name='configsite',
            name='prix_mini',
            field=models.CharField(default='1 000 FCFA', help_text='Prix minimum affiché. Ex: 1 000 FCFA', max_length=100),
        ),
        migrations.AddField(
            model_name='configsite',
            name='stat1_desc',
            field=models.CharField(default='Partout au Bénin', max_length=200),
        ),
        migrations.AddField(
            model_name='configsite',
            name='stat1_icone',
            field=models.CharField(default='👨\u200d👩\u200d👧\u200d👦', max_length=10),
        ),
        migrations.AddField(
            model_name='configsite',
            name='stat1_label',
            field=models.CharField(default='Familles béninoises satisfaites', max_length=200),
        ),
        migrations.AddField(
            model_name='configsite',
            name='stat1_num',
            field=models.CharField(default='500+', max_length=50),
        ),
        migrations.AddField(
            model_name='configsite',
            name='stat2_desc',
            field=models.CharField(default='Sans engrais ni herbicide', max_length=200),
        ),
        migrations.AddField(
            model_name='configsite',
            name='stat2_icone',
            field=models.CharField(default='🌱', max_length=10),
        ),
        migrations.AddField(
            model_name='configsite',
            name='stat2_label',
            field=models.CharField(default='Bio, zéro additif', max_length=200),
        ),
        migrations.AddField(
            model_name='configsite',
            name='stat2_num',
            field=models.CharField(default='100%', max_length=50),
        ),
        migrations.AddField(
            model_name='configsite',
            name='stat3_desc',
            field=models.CharField(default='Enfants, adultes, seniors', max_length=200),
        ),
        migrations.AddField(
            model_name='configsite',
            name='stat3_icone',
            field=models.CharField(default='👶', max_length=10),
        ),
        migrations.AddField(
            model_name='configsite',
            name='stat3_label',
            field=models.CharField(default='Pour toute la famille', max_length=200),
        ),
        migrations.AddField(
            model_name='configsite',
            name='stat3_num',
            field=models.CharField(default='Dès 2 ans', max_length=50),
        ),
        migrations.AddField(
            model_name='configsite',
            name='stat4_desc',
            field=models.CharField(default='Partout au Bénin', max_length=200),
        ),
        migrations.AddField(
            model_name='configsite',
            name='stat4_icone',
            field=models.CharField(default='📦', max_length=10),
        ),
        migrations.AddField(
            model_name='configsite',
            name='stat4_label',
            field=models.CharField(default='Délai de livraison', max_length=200),
        ),
        migrations.AddField(
            model_name='configsite',
            name='stat4_num',
            field=models.CharField(default='24h', max_length=50),
        ),
        migrations.AddField(
            model_name='configsite',
            name='telephone_raw',
            field=models.CharField(default='+2290195967762', help_text='Sans espaces ni +, pour les liens tel: et WhatsApp', max_length=50),
        ),
        migrations.AddField(
            model_name='configsite',
            name='tiktok_url',
            field=models.URLField(blank=True, default='https://www.tiktok.com/@thepio08'),
        ),
        migrations.AddField(
            model_name='faq',
            name='categorie',
            field=models.CharField(blank=True, default='Général', help_text='Ex: Produit, Livraison, Paiement, Santé', max_length=100),
        ),
        migrations.AddField(
            model_name='fondateurconfig',
            name='role',
            field=models.TextField(default='Fondateur · Vétérinaire diplômé\nSpécialiste en biologie cellulaire, Cuba'),
        ),
        migrations.AddField(
            model_name='histoirechapitre',
            name='date_modif',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='histoirechapitre',
            name='numero',
            field=models.CharField(default='01', max_length=10),
        ),
        migrations.AddField(
            model_name='histoirechapitre',
            name='texte',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messagecontact',
            name='objet',
            field=models.CharField(blank=True, choices=[('commande', 'Commande'), ('partenariat', 'Partenariat / Distribution'), ('renseignement', 'Renseignement produit'), ('autre', 'Autre')], max_length=30),
        ),
        migrations.AddField(
            model_name='mission',
            name='texte',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partenaire',
            name='tag',
            field=models.CharField(blank=True, default='Partenaire', max_length=100),
        ),
        migrations.AddField(
            model_name='resetpasswordtoken',
            name='cree_le',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resetpasswordtoken',
            name='expire_le',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slider',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slider',
            name='texte_bouton',
            field=models.CharField(blank=True, default='Voir plus', max_length=100),
        ),
        migrations.AddField(
            model_name='temoignage',
            name='texte',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='temoignage',
            name='type_video',
            field=models.CharField(choices=[('aucune', 'Pas de video'), ('upload', 'Fichier video uploade'), ('lien', 'Lien externe (YouTube / TikTok...)')], default='aucune', max_length=10),
        ),
        migrations.AddField(
            model_name='temoignage',
            name='video_fichier',
            field=models.FileField(blank=True, null=True, upload_to='temoignages/videos/'),
        ),
        migrations.AddField(
            model_name='temoignage',
            name='video_lien',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temoignage',
            name='video_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='temoignages/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='alertestock',
            name='email_alerte',
            field=models.EmailField(blank=True, help_text='Laisser vide = email admin par défaut', max_length=254),
        ),
        migrations.AlterField(
            model_name='alertestock',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='alertestock',
            name='seuil',
            field=models.PositiveIntegerField(default=5, help_text='Envoyer alerte quand stock ≤ seuil'),
        ),
        migrations.AlterField(
            model_name='articleblog',
            name='contenu',
            field=models.TextField(help_text='Contenu complet de l article'),
        ),
        migrations.AlterField(
            model_name='articleblog',
            name='date_publication',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='articleblog',
            name='extrait',
            field=models.TextField(help_text='Resume court (2-3 phrases)'),
        ),
        migrations.AlterField(
            model_name='articleblog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='articleblog',
            name='publie',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='articleblog',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='bienfait',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='bienfait',
            name='icone',
            field=models.CharField(blank=True, help_text='Emoji (copiez-collez un emoji)', max_length=10),
        ),
        migrations.AlterField(
            model_name='bienfait',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bienfait',
            name='titre',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='blacklist',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='codepromo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='codepromo',
            name='limite_utilisations',
            field=models.PositiveIntegerField(blank=True, help_text='Laisser vide = illimité', null=True),
        ),
        migrations.AlterField(
            model_name='codepromo',
            name='valeur',
            field=models.DecimalField(decimal_places=0, help_text='% ou FCFA selon le type', max_digits=10),
        ),
        migrations.AlterField(
            model_name='commande',
            name='code_promo',
            field=models.CharField(blank=True, help_text='Code promo utilisé', max_length=50),
        ),
        migrations.AlterField(
            model_name='commande',
            name='fedapay_ref',
            field=models.CharField(blank=True, help_text='ID transaction Fedapay', max_length=100),
        ),
        migrations.AlterField(
            model_name='commande',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='mode_paiement',
            field=models.CharField(choices=[('mtn_money', 'MTN Money'), ('moov_money', 'Moov Money'), ('wave', 'Wave'), ('orange_money', 'Orange Money'), ('fedapay', 'Fedapay (carte / mobile)'), ('virement', 'Virement bancaire'), ('livraison', 'Paiement a la livraison')], default='livraison', max_length=30),
        ),
        migrations.AlterField(
            model_name='commande',
            name='payee',
            field=models.BooleanField(default=False, help_text='True quand Fedapay confirme le paiement'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='telephone_client',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='configaccueil',
            name='heures_ouverture',
            field=models.CharField(default='Lun – Sam : 8h00 – 18h00', help_text='Horaires affichés dans la colonne Contact du footer.', max_length=200),
        ),
        migrations.AlterField(
            model_name='configaccueil',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='configaccueil',
            name='slogan',
            field=models.CharField(default='Un sang qui circule, une vie qui rayonne.', help_text='Slogan affiché en bas du footer sous le logo.', max_length=300),
        ),
        migrations.AlterField(
            model_name='configsite',
            name='adresse',
            field=models.CharField(default='Oganla Gare Nord, Porto-Novo, Bénin', max_length=300),
        ),
        migrations.AlterField(
            model_name='configsite',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='configsite',
            name='telephone',
            field=models.CharField(default='+229 01 95 96 77 62', max_length=50),
        ),
        migrations.AlterField(
            model_name='faq',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='fondateurconfig',
            name='citation',
            field=models.TextField(default="Le plus grand laboratoire, c'est notre propre corps."),
        ),
        migrations.AlterField(
            model_name='fondateurconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='fondateurconfig',
            name='nom',
            field=models.CharField(default='Felicien Prosper DURAND', max_length=200),
        ),
        migrations.AlterField(
            model_name='fondateurconfig',
            name='photo',
            field=models.ImageField(blank=True, help_text='Photo du fondateur. Taille recommandée : 600x800px.', null=True, upload_to='fondateur/'),
        ),
        migrations.AlterField(
            model_name='histoirechapitre',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='historiquecommande',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lignecommande',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lignecommande',
            name='produit',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='api.produit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='logconnexion',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='logconnexion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='logconnexion',
            name='resultat',
            field=models.CharField(choices=[('succes', 'Succès'), ('echec', 'Échec'), ('bloque', 'Bloqué (throttle)')], max_length=10),
        ),
        migrations.AlterField(
            model_name='logconnexion',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='messagecontact',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='messagecontact',
            name='nom',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='messagecontact',
            name='telephone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='mission',
            name='icone',
            field=models.CharField(blank=True, help_text='Emoji ex: 🌱', max_length=10),
        ),
        migrations.AlterField(
            model_name='mission',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='newsletterabonne',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='paniersauvegarde',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='paniersauvegarde',
            name='utilisateur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='panier_sauvegarde', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='partenaire',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='partenaire',
            name='logo',
            field=models.ImageField(default='', help_text='Logo PNG fond transparent recommande', upload_to='partenaires/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produit',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='produit',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='quantite_min',
            field=models.PositiveIntegerField(default=1, help_text='Quantité minimale de commande'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='0 = stock illimité'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='unite',
            field=models.CharField(default='boite', max_length=50),
        ),
        migrations.AlterField(
            model_name='reponseavis',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='resetpasswordtoken',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='resetpasswordtoken',
            name='token',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='resetpasswordtoken',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reset_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='slider',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(default='', help_text='Taille recommandee : 1920x800px', upload_to='sliders/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='slider',
            name='lien',
            field=models.CharField(blank=True, help_text='Ex: /boutique', max_length=200),
        ),
        migrations.AlterField(
            model_name='slider',
            name='sous_titre',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='temoignage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='temoignage',
            name='note',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='temoignage',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temoignages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='temoignage',
            name='ville',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='telephone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='zonelivraison',
            name='delai',
            field=models.CharField(default='24-48h', help_text='Délai estimé ex: 24-48h', max_length=100),
        ),
        migrations.AlterField(
            model_name='zonelivraison',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='zonelivraison',
            name='prix',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Prix livraison en FCFA', max_digits=8),
        ),
        migrations.AddIndex(
            model_name='logconnexion',
            index=models.Index(fields=['email', 'date'], name='api_logconn_email_f04a1c_idx'),
        ),
    ]
